import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const H={"Content-Type":"application/json"};
const ROUTES:Record<string,string[]>={campaign:["researcher","strategist","copywriter","reviewer"],software:["researcher","programmer","tester","reviewer"],commercial:["researcher","commercial","copywriter","reviewer"],legal:["researcher","legal_reviewer","reviewer"],seo:["researcher","seo_analyst","copywriter","reviewer"],analytics:["analytics","strategist","reviewer"],operations:["strategist","reviewer"]};
const arr=(v:any)=>Array.isArray(v)?v.map(String).map(x=>x.trim()).filter(Boolean):[];
const req=(v:any,n:string)=>{const s=String(v??"").trim();if(!s)throw new Error(`campo obrigatório ausente: ${n}`);return s};
function infer(s:string){const x=` ${s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()} `;if(/ contrato| juridic| clausula| lei /.test(x))return"legal";if(/ sistema| aplicativo| codigo| bug| site| api| banco de dados| integracao| programar /.test(x))return"software";if(/ venda| cliente| lead| proposta commercial| proposta comercial| preco| orcamento /.test(x))return"commercial";if(/ seo | google| palavra-chave| ranking /.test(x))return"seo";if(/ metrica| dashboard| conversao| funil| dados| relatorio /.test(x))return"analytics";if(/ campanha| instagram| reels| anuncio| copy| post| marketing| conteudo /.test(x))return"campaign";return"operations"}
function getPath(v:any,path:string){let c=v;for(const p of(path?path.split("."):[])){if(c&&typeof c==="object"&&p in c)c=c[p];else throw new Error(`referência inválida: ${path}`)}return c}
function refs(v:any,done:Record<string,any>):any{if(Array.isArray(v))return v.map(x=>refs(x,done));if(v&&typeof v==="object"){const k=Object.keys(v);if(k.length===2&&k.includes("$step")&&k.includes("path")){const id=String(v.$step);if(!(id in done))throw new Error(`etapa referenciada não concluída: ${id}`);return getPath(done[id],String(v.path))}return Object.fromEntries(Object.entries(v).map(([a,b])=>[a,refs(b,done)]))}return v}
function out(id:string,actor:string,status:string,data:any,warnings:string[]=[],review=false){return{specialist_id:id,actor_id:actor,status,data,warnings,requires_human_review:review,publication_authorized:false,external_actions_authorized:false}}
function execute(id:string,p:any,actor:string):any{
 if(id==="researcher"){const facts=arr(p.facts);if(!facts.length)throw new Error("researcher exige facts");return out(id,actor,"completed",{facts,sources:Array.isArray(p.sources)?p.sources:[],open_questions:arr(p.questions),external_research_performed:false},["Sem busca externa na Etapa 15."])}
 if(id==="strategist"){const goal=req(p.goal,"goal"),aud=req(p.audience,"audience");return out(id,actor,"completed",{goal,audience:aud,strategy_statement:`Para ${aud}, orientar o trabalho para ${goal.toLowerCase()}.`,priorities:arr(p.priorities).length?arr(p.priorities):["Aderência ao objetivo","Revisão humana"],constraints:arr(p.constraints),facts_used:arr(p.facts),guardrails:["Sem publicação automática","Sem efeitos externos"]})}
 if(id==="copywriter"){const headline=req(p.headline,"headline"),cta=req(p.cta,"cta"),body=arr(p.body_points);if(!body.length)throw new Error("copywriter exige body_points");return out(id,actor,"completed",{headline,short_caption:`${body.map(x=>x.replace(/[. ]+$/,'')+'.').join(' ')} ${cta}`.trim(),call_to_action:cta,facts_used:arr(p.facts)})}
 if(id==="reviewer"){if(!p.artifact||typeof p.artifact!=="object")throw new Error("reviewer exige artifact");const missing=arr(p.required_fields).filter((f:string)=>!p.artifact[f]);const violations=[...missing.map((f:string)=>`campo ausente: ${f}`)];if(p.artifact.publication_authorized===true)violations.push("artifact tentou autorizar publicação");return out(id,actor,"needs_review",{artifact:p.artifact,missing_fields:missing,violations,ready_for_human_review:violations.length===0},violations,true)}
 if(id==="programmer"){const ws:Record<string,string>={...(p.workspace??{})};const ops=Array.isArray(p.operations)?p.operations:[];const changed:any[]=[];for(const op of ops){const path=req(op.path,"operation.path").replaceAll("\\","/");if(path.startsWith("/")||path.includes("../"))throw new Error("caminho inválido");const a=String(op.action??"");if(a==="write_file"){ws[path]=String(op.content??"");changed.push({path,action:"written"})}else if(a==="append_text"){ws[path]=String(ws[path]??"")+String(op.content??"");changed.push({path,action:"appended"})}else if(a==="delete_file"){delete ws[path];changed.push({path,action:"deleted"})}else throw new Error(`ação não permitida: ${a}`)}return out(id,actor,"completed",{workspace:ws,changed_files:changed,operation_count:ops.length})}
 if(id==="tester"){const ws:Record<string,string>=p.workspace??{};const checks=(Array.isArray(p.checks)?p.checks:[]).map((c:any)=>{const path=req(c.path,"check.path"),kind=String(c.kind??"");let passed=false,detail="";if(kind==="file_exists"){passed=path in ws;detail=passed?"arquivo presente":"arquivo ausente"}else if(kind==="json_valid"){try{JSON.parse(String(ws[path]));passed=true;detail="JSON válido"}catch(e){detail=`JSON inválido: ${String(e)}`}}else if(kind==="contains"){passed=String(ws[path]??"").includes(req(c.value,"check.value"));detail=passed?"trecho encontrado":"trecho não encontrado"}else throw new Error(`teste não permitido: ${kind}`);return{kind,path,passed,detail}});const passed=checks.length>0&&checks.every((x:any)=>x.passed);return out(id,actor,passed?"completed":"needs_review",{passed,checks,check_count:checks.length},passed?[]:["Um ou mais testes falharam."],!passed)}
 if(id==="commercial"){const offer=req(p.offer_name,"offer_name"),aud=req(p.audience,"audience"),cta=req(p.cta,"cta"),benefits=arr(p.benefits);if(!benefits.length)throw new Error("commercial exige benefits");return out(id,actor,"completed",{value_proposition:`${offer} ajuda ${aud} a ${benefits[0].toLowerCase()}.`,outreach_script:`Olá! Estou entrando em contato sobre ${offer}. ${benefits[0]}. ${cta}`,facts_used:{benefits,proofs:arr(p.proofs)}})}
 if(id==="legal_reviewer"){const t=req(p.text,"text");const rules:[[string,RegExp]]|any=[["multa",/multa|penalidade/i],["renovacao",/renova[cç][aã]o\s+autom[aá]tica/i],["dados_pessoais",/dados\s+pessoais|lgpd|privacidade/i],["foro",/\bforo\b/i],["exclusividade",/exclusiv/i]];const flags=rules.filter((x:any)=>x[1].test(t)).map((x:any)=>({code:x[0],note:"Ponto identificado para revisão humana."}));return out(id,actor,"needs_review",{jurisdiction:p.jurisdiction??null,risk_flags:flags,flag_count:flags.length},["Triagem automatizada; não substitui advogado."],true)}
 if(id==="seo_analyst"){const topic=req(p.topic,"topic"),primary=req(p.primary_keyword,"primary_keyword"),city=String(p.city??"").trim();const slug=(primary+(city?` ${city}`:"")).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80);return out(id,actor,"completed",{slug,title:`${topic}: ${primary}`.slice(0,60),meta_description:`Entenda ${primary} em ${topic}.`.slice(0,155),h1:topic,outline_h2:[`O que é ${primary}`,`Como ${primary} se aplica a ${topic}`],keywords:{primary,secondary:arr(p.secondary_keywords)}})}
 if(id==="analytics"){const cur=p.current??{},prev=p.previous??{},deltas:Record<string,any>={},alerts:string[]=[];if(!Object.keys(cur).length)throw new Error("analytics exige métricas");for(const[k,v]of Object.entries(cur)){if(typeof v!=="number")throw new Error(`métrica inválida: ${k}`);if(typeof prev[k]==="number"){const pct=prev[k]===0?null:Math.round((((v as number)-prev[k])/prev[k])*10000)/100;deltas[k]={absolute:(v as number)-prev[k],percent:pct};if(pct!==null&&pct<=-20)alerts.push(`${k} caiu ${Math.abs(pct).toFixed(2)}%.`)}}return out(id,actor,"completed",{current:cur,previous:prev,deltas,alerts})}
 throw new Error(`especialista não suportado: ${id}`)
}

async function processJob(client:any,job:any){const p=job.payload??{},actor=String(p.test_actor_id??"");if(p.test_mode!==true||!actor.startsWith("stage8-test-"))throw new Error("guard test-only recusou workflow");if(p.publication_authorized===true||p.external_actions_authorized===true)throw new Error("efeito externo recusado");const work=p.work??{},objective=req(work.objective,"work.objective"),route=work.kind&&work.kind!=="auto"?String(work.kind):infer(objective),ids=ROUTES[route];if(!ids)throw new Error(`rota inválida: ${route}`);
 let {data:wf,error:werr}=await client.from("squad_workflows").select("*").eq("job_id",job.id).maybeSingle();if(werr)throw werr;if(!wf){const ins=await client.from("squad_workflows").insert({job_id:job.id,actor_id:actor,route,objective,status:"running",step_count:ids.length,state:{}}).select("*").single();if(ins.error)throw ins.error;wf=ins.data}
 const stepsRes=await client.from("squad_workflow_steps").select("*").eq("workflow_id",wf.id).order("sequence",{ascending:true});if(stepsRes.error)throw stepsRes.error;const done:Record<string,any>={};for(const s of stepsRes.data??[]){if(["completed","needs_review"].includes(s.status))done[s.specialist_id]=s.result}
 let needs=wf.requires_human_review===true;const start=Number(wf.current_step??0);for(let i=start;i<ids.length;i++){const id=ids[i],raw=p.step_payloads?.[id];if(raw===undefined){await client.from("squad_workflows").update({status:"blocked",last_error:`Payload ausente para ${id}`,updated_at:new Date().toISOString()}).eq("id",wf.id);throw new Error(`Payload ausente para ${id}`)}const input=refs(raw,done);await client.from("squad_jobs").update({heartbeat_at:new Date().toISOString()}).eq("id",job.id);const prev=(stepsRes.data??[]).find((s:any)=>s.sequence===i);const attempt=Number(prev?.attempt??0)+1;const up=await client.from("squad_workflow_steps").upsert({workflow_id:wf.id,sequence:i,specialist_id:id,status:"running",attempt,input,started_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"workflow_id,sequence"});if(up.error)throw up.error;const r=execute(id,input,actor);if(r.publication_authorized||r.external_actions_authorized)throw new Error("especialista violou fail-closed");done[id]=r;needs=needs||r.requires_human_review===true;const fin=await client.from("squad_workflow_steps").update({status:r.status,result:r,error:null,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("workflow_id",wf.id).eq("sequence",i);if(fin.error)throw fin.error;const state={...(wf.state??{})};const shouldInterrupt=p.test_interrupt_once===true&&Number(p.test_interrupt_after_sequence)===i&&state.synthetic_interrupt_done!==true;if(shouldInterrupt){state.synthetic_interrupt_done=true;await client.from("squad_workflows").update({status:"retry",current_step:i+1,completed_steps:i+1,requires_human_review:needs,state,updated_at:new Date().toISOString()}).eq("id",wf.id);await client.from("squad_jobs").update({status:"retry",available_at:new Date().toISOString(),locked_by:null,locked_at:null,heartbeat_at:null,last_error:"synthetic_stage15_interrupt"}).eq("id",job.id);return{interrupted:true,workflow_id:wf.id,resume_from:i+1}}
 await client.from("squad_workflows").update({status:"running",current_step:i+1,completed_steps:i+1,requires_human_review:needs,updated_at:new Date().toISOString()}).eq("id",wf.id)}
 const status=needs?"needs_review":"completed";await client.from("squad_workflows").update({status,current_step:ids.length,completed_steps:ids.length,requires_human_review:needs,completed_at:new Date().toISOString(),updated_at:new Date().toISOString(),last_error:null}).eq("id",wf.id);const summary={workflow_id:wf.id,route,status,durable:true,resumed_from_step:start,step_count:ids.length,requires_human_review:needs,waiting_approval:needs,publication_authorized:false,external_actions_authorized:false,test_actor_id:actor,runtime:"stage15-edge"};await client.from("squad_jobs").update({status:"completed",result:summary,finished_at:new Date().toISOString(),locked_by:null,locked_at:null,heartbeat_at:null,last_error:null}).eq("id",job.id);if(needs)await client.from("squad_runtime_alerts").insert({severity:"info",kind:"stage15_workflow_needs_review",message:"Workflow durável concluído e aguardando revisão humana; publicação bloqueada.",test_actor_id:actor,payload:{workflow_id:wf.id,route,publication_authorized:false}});return summary}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return new Response(JSON.stringify({error:"method_not_allowed"}),{status:405,headers:H});const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return new Response(JSON.stringify({error:"runtime_env_missing"}),{status:500,headers:H});const c=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const token=req.headers.get("x-integrasquad-worker-token")??"";const auth=await c.rpc("squad_verify_stage8_worker_token",{p_token:token});if(auth.error||auth.data!==true)return new Response(JSON.stringify({error:"unauthorized_worker"}),{status:401,headers:H});let body:any={};try{body=await req.json()}catch{}const max=Math.min(Math.max(Number(body.max_jobs??3),1),10),wid=`stage15-edge-${crypto.randomUUID().slice(0,12)}`;const tick=await c.from("squad_runtime_ticks").insert({worker_id:wid,mode:"test",status:"running",detail:{source:"edge_function",stage:15,test_only:true,max_jobs:max}}).select("id").single();if(tick.error||!tick.data)return new Response(JSON.stringify({error:"tick_create_failed"}),{status:500,headers:H});const stats={jobs_claimed:0,jobs_completed:0,jobs_retried:0,jobs_failed:0,stale_jobs_requeued:0};try{const stale=await c.rpc("squad_requeue_stale_stage15_workflow_jobs",{p_stale_seconds:300});if(stale.error)throw stale.error;stats.stale_jobs_requeued=Number(stale.data??0);for(let n=0;n<max;n++){const claim=await c.rpc("squad_claim_next_stage15_workflow_job",{p_worker_id:wid});if(claim.error)throw claim.error;const job=claim.data?.[0];if(!job)break;stats.jobs_claimed++;try{const r=await processJob(c,job);if(r?.interrupted)stats.jobs_retried++;else stats.jobs_completed++}catch(e){const next=Number(job.attempt??0)+1,failed=next>=Number(job.max_attempts??3);await c.from("squad_jobs").update({attempt:next,status:failed?"failed":"retry",available_at:failed?job.available_at:new Date(Date.now()+15000*Math.max(1,next)).toISOString(),finished_at:failed?new Date().toISOString():null,locked_by:null,locked_at:null,heartbeat_at:null,last_error:String(e)}).eq("id",job.id);const wf=await c.from("squad_workflows").select("id").eq("job_id",job.id).maybeSingle();if(wf.data)await c.from("squad_workflows").update({status:failed?"failed":"retry",last_error:String(e),updated_at:new Date().toISOString()}).eq("id",wf.data.id);failed?stats.jobs_failed++:stats.jobs_retried++}}
 await c.from("squad_runtime_ticks").update({...stats,status:"completed",finished_at:new Date().toISOString(),detail:{source:"edge_function",stage:15,test_only:true,durable:true}}).eq("id",tick.data.id);return new Response(JSON.stringify({ok:true,stage:15,test_mode:true,worker_id:wid,...stats}),{headers:H})}catch(e){await c.from("squad_runtime_ticks").update({...stats,status:"failed",finished_at:new Date().toISOString(),detail:{source:"edge_function",stage:15,test_only:true,error:String(e)}}).eq("id",tick.data.id);return new Response(JSON.stringify({error:"worker_failed",detail:String(e)}),{status:500,headers:H})}});
