const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const apiHeaders = {"content-type":"application/json",apikey:SERVICE_ROLE,authorization:`Bearer ${SERVICE_ROLE}`};
function esc(v: unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function isTestActor(v: unknown){return typeof v === "string" && v.startsWith("stage8-test-")}
function when(v: unknown){if(!v)return "—"; const d=new Date(String(v)); return Number.isNaN(d.getTime())?"—":d.toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}
async function rest(path:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:apiHeaders}); if(!r.ok)throw new Error(`PostgREST ${r.status}: ${await r.text()}`); return await r.json()}
async function snapshot(){
 const [jr,tr,ar,xr,pr]=await Promise.all([
  rest("squad_jobs?select=id,job_type,status,attempt,max_attempts,created_at,updated_at,last_error,result,payload&order=created_at.desc&limit=100"),
  rest("squad_runtime_ticks?select=worker_id,status,jobs_claimed,jobs_completed,jobs_retried,jobs_failed,started_at,finished_at,detail&order=started_at.desc&limit=30"),
  rest("squad_runtime_alerts?select=severity,kind,message,test_actor_id,resolved,created_at&order=created_at.desc&limit=50"),
  rest("squad_test_actors?select=id,display_name,email,enabled,metadata,created_at&order=id.asc"),
  rest("squad_approvals?select=id,run_id,content_digest,decision,metadata,created_at,decided_at&order=created_at.desc&limit=50")]);
 const jobs=jr.filter((r:any)=>r?.payload?.test_mode===true&&isTestActor(r?.payload?.test_actor_id));
 const ticks=tr.filter((r:any)=>r?.detail?.test_only===true); const alerts=ar.filter((r:any)=>isTestActor(r?.test_actor_id)); const actors=xr.filter((r:any)=>r?.enabled===true&&isTestActor(r?.id));
 const approvals=pr.filter((r:any)=>r?.metadata?.test_mode===true&&isTestActor(r?.metadata?.test_actor_id)).map((r:any)=>({id:r.id,run_id:r.run_id,decision:r.decision,content_digest:r.content_digest,test_actor_id:r.metadata.test_actor_id,purpose:r.metadata.purpose??null,preview:r.metadata.preview??{},publication_authorized:r.metadata.publication_authorized===true,created_at:r.created_at,decided_at:r.decided_at}));
 const last=ticks[0]?.finished_at??ticks[0]?.started_at??null; const age=last?(Date.now()-new Date(last).getTime())/60000:null; const health=age===null?"idle":age<=12&&ticks[0]?.status!=="failed"?"healthy":"degraded";
 const waitingJobs=jobs.filter((j:any)=>j?.result?.waiting_approval===true).length; const pendingApprovals=approvals.filter((a:any)=>a.decision==="pending").length;
 return {test_mode:true,generated_at:new Date().toISOString(),health,last_worker_tick_at:last,actors,summary:{jobs_total:jobs.length,completed:jobs.filter((j:any)=>j.status==="completed").length,retrying:jobs.filter((j:any)=>j.status==="retry").length,failed:jobs.filter((j:any)=>j.status==="failed").length,pending:jobs.filter((j:any)=>["pending","running"].includes(j.status)).length,waiting_approval:Math.max(waitingJobs,pendingApprovals),unresolved_alerts:alerts.filter((a:any)=>a.resolved!==true).length},jobs:jobs.slice(0,30).map((j:any)=>({id:j.id,job_type:j.job_type,status:j.status,attempt:j.attempt,max_attempts:j.max_attempts,test_actor_id:j?.payload?.test_actor_id??null,created_at:j.created_at,updated_at:j.updated_at,last_error:j.last_error,result:j.result??{}})),approvals:approvals.slice(0,20),ticks:ticks.slice(0,20),alerts:alerts.slice(0,20)};
}
function html(d:any){
 const rows=d.approvals.map((a:any)=>`<tr><td>${esc(a.decision)}</td><td>${esc(a.test_actor_id)}</td><td>${esc(a.preview?.headline??"—")}</td><td>${esc(a.preview?.call_to_action??"—")}</td><td>${a.publication_authorized?"SIM":"NÃO"}</td><td>${esc(when(a.created_at))}</td></tr>`).join("")||`<tr><td colspan="6">Nenhuma aprovação sintética.</td></tr>`;
 return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IntegraSquad · Aprovações</title><style>body{font:14px system-ui;background:#08111f;color:#eaf2ff;padding:24px}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #20314a;text-align:left}.b{color:#c8c0ff}</style></head><body><h1>IntegraSquad · Sala de Controle</h1><p class="b">🧪 TEST MODE · somente leitura · ${esc(d.health)}</p><p>Jobs: ${esc(d.summary.jobs_total)} · aguardando aprovação: ${esc(d.summary.waiting_approval)}</p><h2>Fila de aprovação</h2><table><thead><tr><th>Decisão</th><th>Ator</th><th>Headline</th><th>CTA</th><th>Publicação</th><th>Criado</th></tr></thead><tbody>${rows}</tbody></table><p>Este painel não possui controles de publicação ou mutação.</p></body></html>`;
}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:{"access-control-allow-origin":"*"}}); if(!SUPABASE_URL||!SERVICE_ROLE)return new Response("runtime_not_configured",{status:503}); try{const d=await snapshot(); const u=new URL(req.url); if(u.searchParams.get("format")==="json")return new Response(JSON.stringify(d),{headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*","x-integrasquad-mode":"test-only"}}); return new Response(html(d),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-integrasquad-mode":"test-only"}})}catch(e){return new Response(JSON.stringify({test_mode:true,error:"dashboard_unavailable",detail:String(e)}),{status:500,headers:{"content-type":"application/json","access-control-allow-origin":"*"}})}});
