const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const apiHeaders = {"content-type":"application/json",apikey:SERVICE_ROLE,authorization:`Bearer ${SERVICE_ROLE}`};
function esc(v: unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function isTestActor(v: unknown){return typeof v === "string" && v.startsWith("stage8-test-")}
function when(v: unknown){if(!v)return "—"; const d=new Date(String(v)); return Number.isNaN(d.getTime())?"—":d.toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}
async function rest(path:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:apiHeaders}); if(!r.ok)throw new Error(`PostgREST ${r.status}: ${await r.text()}`); return await r.json()}
async function snapshot(){
 const [jr,tr,ar,xr,pr,wr,sr]=await Promise.all([
  rest("squad_jobs?select=id,job_type,status,attempt,max_attempts,created_at,updated_at,last_error,result,payload&order=created_at.desc&limit=200"),
  rest("squad_runtime_ticks?select=worker_id,status,jobs_claimed,jobs_completed,jobs_retried,jobs_failed,started_at,finished_at,detail&order=started_at.desc&limit=60"),
  rest("squad_runtime_alerts?select=severity,kind,message,test_actor_id,resolved,created_at&order=created_at.desc&limit=100"),
  rest("squad_test_actors?select=id,display_name,email,enabled,metadata,created_at&order=id.asc"),
  rest("squad_approvals?select=id,run_id,content_digest,decision,metadata,created_at,decided_at&order=created_at.desc&limit=50"),
  rest("squad_workflows?select=id,job_id,actor_id,route,objective,status,current_step,step_count,completed_steps,requires_human_review,publication_authorized,external_actions_authorized,state,last_error,updated_at,completed_at&order=updated_at.desc&limit=50"),
  rest("squad_workflow_steps?select=workflow_id,sequence,specialist_id,status,attempt,error,updated_at&order=updated_at.desc&limit=200")]);
 const jobs=jr.filter((r:any)=>r?.payload?.test_mode===true&&isTestActor(r?.payload?.test_actor_id));
 const ticks=tr.filter((r:any)=>r?.detail?.test_only===true); const alerts=ar.filter((r:any)=>isTestActor(r?.test_actor_id)); const actors=xr.filter((r:any)=>r?.enabled===true&&isTestActor(r?.id));
 const approvals=pr.filter((r:any)=>r?.metadata?.test_mode===true&&isTestActor(r?.metadata?.test_actor_id)).map((r:any)=>({id:r.id,run_id:r.run_id,decision:r.decision,test_actor_id:r.metadata.test_actor_id,preview:r.metadata.preview??{},publication_authorized:r.metadata.publication_authorized===true,created_at:r.created_at,decided_at:r.decided_at}));
 const specialistJobs=jobs.filter((j:any)=>String(j.job_type??"").startsWith("specialist."));
 const specialists=specialistJobs.slice(0,30).map((j:any)=>({id:j.id,specialist_id:String(j.job_type).replace("specialist.",""),status:j.status,specialist_status:j?.result?.specialist_status??null,requires_human_review:j?.result?.requires_human_review===true,test_actor_id:j?.payload?.test_actor_id??null,updated_at:j.updated_at??j.created_at,last_error:j.last_error}));
 const workflowJobs=jobs.filter((j:any)=>j.job_type==="maestro.workflow");
 const workflows=workflowJobs.slice(0,30).map((j:any)=>({id:j.id,status:j.status,route:j?.result?.workflow?.route??j?.payload?.work?.kind??null,workflow_status:j?.result?.workflow?.status??null,step_count:Array.isArray(j?.result?.workflow?.steps)?j.result.workflow.steps.length:0,requires_human_review:j?.result?.workflow?.requires_human_review===true,test_actor_id:j?.payload?.test_actor_id??null,updated_at:j.updated_at??j.created_at,last_error:j.last_error,publication_authorized:j?.result?.publication_authorized===true}));
 const durableWorkflows=wr.filter((w:any)=>isTestActor(w.actor_id)).map((w:any)=>({...w,steps:sr.filter((s:any)=>s.workflow_id===w.id).sort((a:any,b:any)=>a.sequence-b.sequence)}));
 const last=ticks[0]?.finished_at??ticks[0]?.started_at??null; const age=last?(Date.now()-new Date(last).getTime())/60000:null; const health=age===null?"idle":age<=12&&ticks[0]?.status!=="failed"?"healthy":"degraded";
 const waitingJobs=jobs.filter((j:any)=>j?.result?.waiting_approval===true).length; const pendingApprovals=approvals.filter((a:any)=>a.decision==="pending").length;
 return {test_mode:true,stage:15,generated_at:new Date().toISOString(),health,last_worker_tick_at:last,actors,summary:{jobs_total:jobs.length,specialist_jobs:specialistJobs.length,workflow_jobs:workflowJobs.length,durable_workflows:durableWorkflows.length,completed:jobs.filter((j:any)=>j.status==="completed").length,retrying:jobs.filter((j:any)=>j.status==="retry").length,failed:jobs.filter((j:any)=>j.status==="failed").length,pending:jobs.filter((j:any)=>["pending","running"].includes(j.status)).length,waiting_approval:Math.max(waitingJobs,pendingApprovals),unresolved_alerts:alerts.filter((a:any)=>a.resolved!==true).length},jobs:jobs.slice(0,50),specialists,workflows,durable_workflows:durableWorkflows,approvals:approvals.slice(0,20),ticks:ticks.slice(0,30),alerts:alerts.slice(0,30)};
}
function html(d:any){const dw=d.durable_workflows.map((w:any)=>`<tr><td>${esc(w.route)}</td><td>${esc(w.status)}</td><td>${esc(w.completed_steps)}/${esc(w.step_count)}</td><td>${esc(w.actor_id)}</td><td>${w.requires_human_review?"SIM":"NÃO"}</td><td>🔒 NÃO</td><td>${esc(when(w.updated_at))}</td></tr>`).join("")||`<tr><td colspan="7">Nenhum workflow durável.</td></tr>`;const wr=d.workflows.map((w:any)=>`<tr><td>${esc(w.route??"—")}</td><td>${esc(w.status)}</td><td>${esc(w.workflow_status??"—")}</td><td>${esc(w.step_count)}</td><td>${esc(w.test_actor_id)}</td><td>${w.requires_human_review?"SIM":"NÃO"}</td><td>${w.publication_authorized?"⚠️ SIM":"🔒 NÃO"}</td></tr>`).join("")||`<tr><td colspan="7">Nenhum workflow legado.</td></tr>`;return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IntegraSquad · Etapa 15</title><style>body{font:14px system-ui;background:#08111f;color:#eaf2ff;padding:24px}table{width:100%;border-collapse:collapse;margin-bottom:28px}td,th{padding:10px;border-bottom:1px solid #20314a;text-align:left}.b{color:#c8c0ff}</style></head><body><h1>IntegraSquad · Sala de Controle</h1><p class="b">🧪 ETAPA 15 · TEST MODE · workflows duráveis · ${esc(d.health)}</p><p>Jobs: ${esc(d.summary.jobs_total)} · workflows duráveis: ${esc(d.summary.durable_workflows)} · especialistas: ${esc(d.summary.specialist_jobs)}</p><h2>Workflows duráveis</h2><table><thead><tr><th>Rota</th><th>Status</th><th>Progresso</th><th>Ator</th><th>Revisão</th><th>Publicação</th><th>Atualizado</th></tr></thead><tbody>${dw}</tbody></table><h2>Workflows Etapa 14</h2><table><thead><tr><th>Rota</th><th>Job</th><th>Workflow</th><th>Etapas</th><th>Ator</th><th>Revisão</th><th>Publicação</th></tr></thead><tbody>${wr}</tbody></table><p>Nenhum controle de publicação ou mutação é exposto.</p></body></html>`;}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:{"access-control-allow-origin":"*"}}); if(!SUPABASE_URL||!SERVICE_ROLE)return new Response("runtime_not_configured",{status:503}); try{const d=await snapshot(); const u=new URL(req.url); if(u.searchParams.get("format")==="json")return new Response(JSON.stringify(d),{headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*","x-integrasquad-mode":"test-only"}}); return new Response(html(d),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-integrasquad-mode":"test-only"}})}catch(e){return new Response(JSON.stringify({test_mode:true,error:"dashboard_unavailable",detail:String(e)}),{status:500,headers:{"content-type":"application/json","access-control-allow-origin":"*"}})}});
