create table if not exists public.squad_runs (
  id uuid primary key default gen_random_uuid(),
  goal text not null,
  status text not null default 'pending' check (status in ('pending','running','completed','failed','waiting_approval','cancelled')),
  current_stage text,
  context jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.squad_tasks (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.squad_runs(id) on delete cascade,
  sequence integer not null check (sequence >= 0),
  agent_id text not null,
  objective text not null,
  status text not null default 'pending' check (status in ('pending','running','completed','failed','waiting_approval','cancelled')),
  input jsonb not null default '{}'::jsonb,
  result_summary text,
  result_data jsonb not null default '{}'::jsonb,
  error text,
  attempt integer not null default 0 check (attempt >= 0),
  max_attempts integer not null default 3 check (max_attempts > 0),
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(run_id, sequence)
);

create table if not exists public.squad_artifacts (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.squad_runs(id) on delete cascade,
  task_id uuid references public.squad_tasks(id) on delete cascade,
  type text not null,
  path_or_url text not null,
  checksum_sha256 text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.squad_events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.squad_runs(id) on delete cascade,
  task_id uuid references public.squad_tasks(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.squad_checkpoints (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.squad_runs(id) on delete cascade,
  checkpoint_key text not null,
  resume_sequence integer check (resume_sequence is null or resume_sequence >= 0),
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(run_id, checkpoint_key)
);

create table if not exists public.squad_memories (
  id uuid primary key default gen_random_uuid(),
  scope text not null,
  memory_key text not null,
  content jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(scope, memory_key)
);

create index if not exists idx_squad_runs_status on public.squad_runs(status);
create index if not exists idx_squad_runs_updated_at on public.squad_runs(updated_at desc);
create index if not exists idx_squad_tasks_run_status on public.squad_tasks(run_id, status);
create index if not exists idx_squad_tasks_agent on public.squad_tasks(agent_id);
create index if not exists idx_squad_artifacts_run on public.squad_artifacts(run_id);
create index if not exists idx_squad_events_run_created on public.squad_events(run_id, created_at);
create index if not exists idx_squad_checkpoints_run on public.squad_checkpoints(run_id);
create index if not exists idx_squad_memories_scope on public.squad_memories(scope);

create or replace function public.squad_touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_squad_runs_touch on public.squad_runs;
create trigger trg_squad_runs_touch before update on public.squad_runs
for each row execute function public.squad_touch_updated_at();

drop trigger if exists trg_squad_tasks_touch on public.squad_tasks;
create trigger trg_squad_tasks_touch before update on public.squad_tasks
for each row execute function public.squad_touch_updated_at();

drop trigger if exists trg_squad_checkpoints_touch on public.squad_checkpoints;
create trigger trg_squad_checkpoints_touch before update on public.squad_checkpoints
for each row execute function public.squad_touch_updated_at();

drop trigger if exists trg_squad_memories_touch on public.squad_memories;
create trigger trg_squad_memories_touch before update on public.squad_memories
for each row execute function public.squad_touch_updated_at();

alter table public.squad_runs enable row level security;
alter table public.squad_tasks enable row level security;
alter table public.squad_artifacts enable row level security;
alter table public.squad_events enable row level security;
alter table public.squad_checkpoints enable row level security;
alter table public.squad_memories enable row level security;

comment on table public.squad_runs is 'Execucoes persistentes do IntegraSquad.';
comment on table public.squad_tasks is 'Tarefas ordenadas por agente dentro de cada run.';
comment on table public.squad_artifacts is 'Artefatos produzidos por tarefas do IntegraSquad.';
comment on table public.squad_events is 'Log append-only de eventos de execucao.';
comment on table public.squad_checkpoints is 'Snapshots usados para retomar execucoes interrompidas.';
comment on table public.squad_memories is 'Memoria estruturada persistente por escopo e chave.';
