import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const jsonHeaders = { "Content-Type": "application/json" };
const allowed = new Set(["programmer","tester","commercial","legal_reviewer","seo_analyst","analytics"]);
function n(v: unknown, f=5){const x=Number(v);return Number.isFinite(x)?Math.trunc(x):f}
function req(v: unknown, field:string){const s=String(v??"").trim();if(!s)throw new Error(`campo obrigatório ausente: ${field}`);return s}
function path(v:unknown){const p=req(v,"path").replaceAll("\\","/");if(p.startsWith("/")||p.startsWith("../")||p.includes("/../"))throw new Error("caminho inválido");return p}
function envelope(id:string,actor:string,status:string,data:Record<string,unknown>,warnings:string[]=[],review=false){return{specialist_id:id,specialist_status:status,specialist_result:{specialist_id:id,actor_id:actor,status,data,warnings,requires_human_review:review,publication_authorized:false,external_actions_authorized:false},requires_human_review:review,waiting_approval:review,publication_authorized:false,external_actions_authorized:false,test_actor_id:actor,runtime:"stage13-edge"}}
function execute(jobType:string,payload:Record<string,unknown>,actor:string){
 if(payload.publication_authorized===true||payload.external_actions_authorized===true)throw new Error("autorização externa recusada");
 req(payload.objective,"objective"); const p=(payload.specialist_payload??{}) as Record<string,unknown>; const id=jobType.replace("specialist.",""); if(!allowed.has(id))throw new Error(`especialista não permitido: ${id}`);
 if(id==="programmer"){const workspace={...((p.workspace??{}) as Record<string,string>)};const ops=Array.isArray(p.operations)?p.operations as Record<string,unknown>[]:[];const changed:Record<string,unknown>[]=[];ops.forEach((op,i)=>{const a=String(op.action??"");const file=path(op.path);if(a==="write_file"){const existed=file in workspace;workspace[file]=String(op.content??"");changed.push({path:file,action:existed?"updated":"created"})}else if(a==="append_text"){workspace[file]=String(workspace[file]??"")+String(op.content??"");changed.push({path:file,action:"appended"})}else if(a==="replace_text"){if(!(file in workspace))throw new Error(`arquivo não existe: ${file}`);const old=req(op.old,`operations[${i}].old`);if(!workspace[file].includes(old))throw new Error(`trecho não encontrado: ${file}`);workspace[file]=workspace[file].replaceAll(old,String(op.new??""));changed.push({path:file,action:"replaced"})}else if(a==="delete_file"){if(!(file in workspace))throw new Error(`arquivo não existe: ${file}`);delete workspace[file];changed.push({path:file,action:"deleted"})}else throw new Error(`ação não permitida: ${a}`)});return envelope(id,actor,"completed",{workspace,changed_files:changed,operation_count:ops.length})}
 if(id==="tester"){const workspace=(p.workspace??{}) as Record<string,string>;const checks=Array.isArray(p.checks)?p.checks as Record<string,unknown>[]:[];const results=checks.map(c=>{const kind=String(c.kind??"");const file=path(c.path);const content=workspace[file];let passed=false,detail="";if(kind==="file_exists"){passed=file in workspace;detail=passed?"arquivo presente":"arquivo ausente"}else if(kind==="file_not_exists"){passed=!(file in workspace);detail=passed?"arquivo ausente":"arquivo ainda presente"}else if(kind==="contains"||kind==="not_contains"){const needle=req(c.value,"check.value");const contains=typeof content==="string"&&content.includes(needle);passed=kind==="contains"?contains:!contains;detail=contains?"trecho encontrado":"trecho não encontrado"}else if(kind==="json_valid"){try{JSON.parse(String(content));passed=true;detail="JSON válido"}catch(e){detail=`JSON inválido: ${String(e)}`}}else if(kind==="python_compile"){passed=false;detail="python_compile disponível apenas no runtime Python canônico"}else throw new Error(`teste não permitido: ${kind}`);return{kind,path:file,passed,detail}});const passed=results.length>0&&results.every(r=>r.passed);return envelope(id,actor,passed?"completed":"needs_review",{passed,checks:results,check_count:results.length},passed?[]:["Um ou mais critérios falharam."],!passed)}
 if(id==="commercial"){const offer=req(p.offer_name,"offer_name"),audience=req(p.audience,"audience"),cta=req(p.cta,"cta");const benefits=Array.isArray(p.benefits)?p.benefits.map(String).filter(Boolean):[];const proofs=Array.isArray(p.proofs)?p.proofs.map(String).filter(Boolean):[];if(!benefits.length)throw new Error("ao menos um benefício é obrigatório");const parts=[`Olá! Estou entrando em contato sobre ${offer}.`,`Para ${audience}, a proposta é: ${benefits[0]}.`];if(benefits.length>1)parts.push(`Outros pontos: ${benefits.slice(1,3).join("; ")}.`);if(proofs.length)parts.push(`Base disponível: ${proofs.slice(0,2).join("; ")}.`);parts.push(cta);return envelope(id,actor,"completed",{value_proposition:`${offer} ajuda ${audience} a ${benefits[0].toLowerCase()}.`,outreach_script:parts.join(" "),facts_used:{benefits,proofs}},proofs.length?[]:["Nenhuma prova fornecida; nenhum resultado foi inventado."])}
 if(id==="legal_reviewer"){const source=req(p.text,"text");const rules:[[string,RegExp],...Array<[string,RegExp]>]=[["exclusividade",/exclusiv/i],["multa",/multa|penalidade/i],["renovacao",/renova[cç][aã]o\s+autom[aá]tica/i],["rescisao",/rescis[aã]o|rescind/i],["foro",/\bforo\b/i],["dados_pessoais",/dados\s+pessoais|lgpd|privacidade/i],["garantia",/garantia\s+(total|absoluta|integral)|garantimos/i],["irrevogavel",/irrevog[aá]vel|irretrat[aá]vel/i]];const flags=rules.filter(([,rx])=>rx.test(source)).map(([code])=>({code,note:"Ponto identificado para revisão humana."}));return envelope(id,actor,"needs_review",{jurisdiction:p.jurisdiction??null,risk_flags:flags,flag_count:flags.length},["Triagem automatizada; não substitui advogado."],true)}
 if(id==="seo_analyst"){const topic=req(p.topic,"topic"),primary=req(p.primary_keyword,"primary_keyword"),brand=String(p.brand??"").trim(),city=String(p.city??"").trim();const secondary=Array.isArray(p.secondary_keywords)?p.secondary_keywords.map(String).filter(Boolean):[];const slug=(primary+(city?` ${city}`:"")).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80);const title=`${topic}: ${primary}${brand?` | ${brand}`:""}`.slice(0,60),meta=`Entenda ${primary} em ${topic}.${city?` Conteúdo voltado para ${city}.`:""} Veja pontos principais e próximos passos.`.slice(0,155);return envelope(id,actor,"completed",{slug,title,meta_description:meta,h1:topic,outline_h2:[`O que é ${primary}`,`Como ${primary} se aplica a ${topic}`,...secondary.slice(0,4).map(k=>`${k}: pontos importantes`)],keywords:{primary,secondary}})}
 const current=(p.current??{}) as Record<string,number>,previous=(p.previous??{}) as Record<string,number>;if(!Object.keys(current).length)throw new Error("ao menos uma métrica atual é obrigatória");const deltas:Record<string,unknown>={},alerts:string[]=[];for(const [key,value]of Object.entries(current)){if(typeof value!=="number")throw new Error(`métrica não numérica: ${key}`);if(typeof previous[key]==="number"){const before=previous[key];const pct=before===0?null:Math.round(((value-before)/before)*10000)/100;deltas[key]={absolute:value-before,percent:pct};if(pct!==null&&pct<=-20)alerts.push(`${key} caiu ${Math.abs(pct).toFixed(2)}% versus período anterior.`)}}const funnel:Record<string,number|null>={};if(typeof current.visits==="number"&&typeof current.leads==="number")funnel.visit_to_lead_percent=current.visits===0?null:Math.round((current.leads/current.visits)*10000)/100;if(typeof current.leads==="number"&&typeof current.conversions==="number")funnel.lead_to_conversion_percent=current.leads===0?null:Math.round((current.conversions/current.leads)*10000)/100;return envelope(id,actor,"completed",{current,previous,deltas,funnel,alerts},["Métricas calculadas apenas a partir dos valores fornecidos."])
}
Deno.serve(async(req:Request)=>{
 if(req.method!=="POST")return new Response(JSON.stringify({error:"method_not_allowed"}),{status:405,headers:jsonHeaders});
 const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return new Response(JSON.stringify({error:"runtime_env_missing"}),{status:500,headers:jsonHeaders});const client=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
 const token=req.headers.get("x-integrasquad-worker-token")??"";const{data:ok,error:authError}=await client.rpc("squad_verify_stage8_worker_token",{p_token:token});if(authError||ok!==true)return new Response(JSON.stringify({error:"unauthorized_worker"}),{status:401,headers:jsonHeaders});
 let body:Record<string,unknown>={};try{body=await req.json()}catch{}const maxJobs=Math.min(Math.max(n(body.max_jobs),1),10),workerId=`stage13-edge-${crypto.randomUUID().slice(0,12)}`;const{data:tick,error:tickError}=await client.from("squad_runtime_ticks").insert({worker_id:workerId,mode:"test",status:"running",detail:{source:"edge_function",stage:13,test_only:true,max_jobs:maxJobs}}).select("id").single();if(tickError||!tick)return new Response(JSON.stringify({error:"tick_create_failed"}),{status:500,headers:jsonHeaders});const stats={jobs_claimed:0,jobs_completed:0,jobs_retried:0,jobs_failed:0,schedules_materialized:0,stale_jobs_requeued:0};
 try{const m=await client.rpc("squad_materialize_due_stage13_specialist_schedules",{p_limit:25});if(m.error)throw m.error;stats.schedules_materialized=Number(m.data??0);const s=await client.rpc("squad_requeue_stale_stage13_specialist_jobs",{p_stale_seconds:300});if(s.error)throw s.error;stats.stale_jobs_requeued=Number(s.data??0);for(let i=0;i<maxJobs;i++){const c=await client.rpc("squad_claim_next_stage13_specialist_job",{p_worker_id:workerId});if(c.error)throw c.error;const job=Array.isArray(c.data)?c.data[0]:c.data;if(!job)break;stats.jobs_claimed++;const payload=(job.payload??{})as Record<string,unknown>,actor=String(payload.test_actor_id??"");try{if(payload.test_mode!==true||!actor.startsWith("stage8-test-"))throw new Error("guard test-only recusou job");const result=execute(job.job_type,payload,actor);await client.from("squad_jobs").update({status:"completed",result,finished_at:new Date().toISOString(),locked_by:null,locked_at:null,heartbeat_at:null,last_error:null}).eq("id",job.id);stats.jobs_completed++;if(result.requires_human_review===true)await client.from("squad_runtime_alerts").insert({test_actor_id:actor,job_id:job.id,severity:"info",kind:"specialist_needs_review",message:"Especialista sintético concluiu com revisão humana obrigatória; publicação permanece bloqueada.",payload:{specialist_id:result.specialist_id,publication_authorized:false}})}catch(e){await client.from("squad_jobs").update({status:"failed",last_error:String(e instanceof Error?e.message:e),finished_at:new Date().toISOString(),locked_by:null,locked_at:null,heartbeat_at:null}).eq("id",job.id);stats.jobs_failed++}}
 await client.from("squad_runtime_ticks").update({...stats,status:"completed",finished_at:new Date().toISOString(),detail:{source:"edge_function",stage:13,test_only:true}}).eq("id",tick.id);return new Response(JSON.stringify({ok:true,worker_id:workerId,stage:13,test_only:true,...stats}),{status:200,headers:jsonHeaders})}catch(e){const message=String(e instanceof Error?e.message:e);await client.from("squad_runtime_ticks").update({...stats,status:"failed",finished_at:new Date().toISOString(),detail:{source:"edge_function",stage:13,test_only:true,error:message}}).eq("id",tick.id);return new Response(JSON.stringify({ok:false,error:message}),{status:500,headers:jsonHeaders})}
});
